# Generated by Django 4.2 on 2023-05-01 19:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="confirmation_code",
            field=models.CharField(null=True, verbose_name="Confirmation Code"),
        ),
    ]
